
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gdato.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int id = 9;
  public static final int cadena = 8;
  public static final int slash = 4;
  public static final int EOF = 0;
  public static final int open = 2;
  public static final int pr_lista = 5;
  public static final int numero = 7;
  public static final int error = 1;
  public static final int pr_principal = 6;
  public static final int close = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "open",
  "close",
  "slash",
  "pr_lista",
  "pr_principal",
  "numero",
  "cadena",
  "id"
  };
}

