/* The following code was generated by JFlex 1.6.1 */

package gxml.analizador;

import java_cup.runtime.Symbol;
import otros.Constante;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/gxml/analizador/gxmlScanner.jflex</tt>
 */
public class gxmlScanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int CADENA = 2;
  public static final int CARACTER = 4;
  public static final int LLAMADA = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\5\1\6\1\7\1\5\22\0\1\1\1\0\1\12"+
    "\1\4\1\11\2\0\1\13\5\0\1\46\1\3\1\17\12\2\2\0"+
    "\1\15\1\20\1\16\2\0\1\27\1\42\1\33\1\34\1\31\1\40"+
    "\1\45\1\44\1\21\2\0\1\36\1\22\1\32\1\24\1\23\1\0"+
    "\1\25\1\37\1\26\1\41\1\30\1\0\1\35\1\43\2\0\1\47"+
    "\4\0\1\27\1\42\1\33\1\34\1\31\1\40\1\45\1\44\1\21"+
    "\2\0\1\36\1\22\1\32\1\24\1\23\1\0\1\25\1\37\1\26"+
    "\1\41\1\30\1\0\1\35\1\43\1\0\1\14\1\10\1\50\7\0"+
    "\1\6\252\0\2\21\115\0\1\37\u1ea8\0\1\6\1\6\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\13\1\1\13\3\1\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\15\1\23"+
    "\4\0\1\24\30\0\1\25\1\26\1\27\1\30\1\2"+
    "\10\0\1\31\32\0\1\32\1\0\1\33\3\0\1\34"+
    "\11\0\1\35\7\0\1\2\5\0\1\36\1\37\11\0"+
    "\1\40\3\0\1\41\1\0\1\42\1\43\1\0\1\44"+
    "\1\45\2\0\1\46\3\0\1\47\1\50\6\0\1\51"+
    "\7\0\1\52\1\53\1\54\1\0\1\55\1\56\1\0"+
    "\1\57\15\0\1\60\1\0\1\61\1\62\1\63\3\0"+
    "\1\64\1\0\1\65\3\0\1\66\4\0\1\67";

  private static int [] zzUnpackAction() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\244\0\244\0\315\0\366"+
    "\0\244\0\244\0\244\0\244\0\244\0\244\0\244\0\u011f"+
    "\0\u0148\0\u0171\0\u019a\0\u01c3\0\u01ec\0\u0215\0\u023e\0\u0267"+
    "\0\u0290\0\u02b9\0\244\0\u02e2\0\u030b\0\u0334\0\244\0\u035d"+
    "\0\244\0\244\0\u0386\0\244\0\244\0\u03af\0\244\0\u03d8"+
    "\0\u0401\0\u042a\0\u0453\0\244\0\u047c\0\u04a5\0\u04ce\0\u04f7"+
    "\0\u0520\0\u0549\0\u0572\0\u059b\0\u05c4\0\u05ed\0\u0616\0\u063f"+
    "\0\u0668\0\u0691\0\u06ba\0\u06e3\0\u070c\0\u0735\0\u075e\0\u0787"+
    "\0\u07b0\0\u07d9\0\u0802\0\u082b\0\244\0\244\0\244\0\u03d8"+
    "\0\u0401\0\u0854\0\u087d\0\u08a6\0\u08cf\0\u08f8\0\u0921\0\u094a"+
    "\0\u0973\0\244\0\u099c\0\u09c5\0\u09ee\0\u0a17\0\u0a40\0\u0a69"+
    "\0\u0a92\0\u0abb\0\u0ae4\0\u0b0d\0\u0b36\0\u0b5f\0\u0b88\0\u0bb1"+
    "\0\u0bda\0\u0c03\0\u0c2c\0\u0c55\0\u0c7e\0\u0ca7\0\u0cd0\0\u0cf9"+
    "\0\u0d22\0\u0d4b\0\u0d74\0\u0d9d\0\244\0\u0dc6\0\244\0\u0def"+
    "\0\u0e18\0\u0e41\0\244\0\u0e6a\0\u0e93\0\u0ebc\0\u0ee5\0\u0f0e"+
    "\0\u0f37\0\u0f60\0\u0f89\0\u0fb2\0\244\0\u0fdb\0\u1004\0\u102d"+
    "\0\u1056\0\u107f\0\u10a8\0\u10d1\0\u10d1\0\u10fa\0\u1123\0\u114c"+
    "\0\u1175\0\u119e\0\244\0\244\0\u11c7\0\u11f0\0\u1219\0\u1242"+
    "\0\u126b\0\u1294\0\u12bd\0\u12e6\0\u130f\0\244\0\u1338\0\u1361"+
    "\0\u138a\0\244\0\u13b3\0\244\0\244\0\u13dc\0\244\0\244"+
    "\0\u1405\0\u142e\0\u1457\0\u1480\0\u14a9\0\u14d2\0\244\0\244"+
    "\0\u14fb\0\u1524\0\u154d\0\u1576\0\u159f\0\u15c8\0\244\0\u15f1"+
    "\0\u161a\0\u1643\0\u166c\0\u1695\0\u16be\0\u16e7\0\244\0\244"+
    "\0\244\0\u1710\0\244\0\244\0\u1739\0\244\0\u1762\0\u178b"+
    "\0\u17b4\0\u17dd\0\u1806\0\u182f\0\u1858\0\u1881\0\u18aa\0\u18d3"+
    "\0\u18fc\0\u1925\0\u194e\0\244\0\u1977\0\244\0\244\0\244"+
    "\0\u19a0\0\u19c9\0\u19f2\0\244\0\u1a1b\0\244\0\u1a44\0\u1a6d"+
    "\0\u1a96\0\244\0\u1abf\0\u1ae8\0\u1b11\0\u1b3a\0\244";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\1\6\1\7\1\5\1\10\1\6\1\0\1\6"+
    "\2\5\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\5\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\5\1\35"+
    "\1\5\1\36\1\37\5\5\5\40\1\0\4\40\1\41"+
    "\1\42\33\40\1\43\6\40\1\0\4\40\1\44\1\45"+
    "\33\40\1\43\1\40\50\46\1\47\53\0\1\7\1\50"+
    "\51\0\1\51\4\0\1\52\61\0\1\53\11\0\1\54"+
    "\35\0\1\55\5\0\1\56\11\0\1\57\36\0\1\60"+
    "\52\0\1\61\40\0\1\62\5\0\1\63\1\0\1\64"+
    "\51\0\1\65\1\66\2\0\1\67\2\0\1\70\40\0"+
    "\1\71\51\0\1\72\42\0\1\73\4\0\1\74\43\0"+
    "\1\75\14\0\1\76\36\0\1\77\1\0\1\100\40\0"+
    "\1\101\56\0\1\102\11\0\1\103\33\0\1\104\24\0"+
    "\5\40\1\0\4\40\2\0\33\40\1\0\1\40\12\0"+
    "\1\44\1\42\11\0\1\105\1\106\3\0\1\107\16\0"+
    "\50\46\3\0\1\110\46\0\5\51\1\6\2\0\1\111"+
    "\40\51\11\52\1\112\37\52\23\0\1\113\57\0\1\114"+
    "\53\0\1\115\51\0\1\116\40\0\1\117\62\0\1\120"+
    "\33\0\1\121\47\0\1\122\63\0\1\123\46\0\1\124"+
    "\50\0\1\125\43\0\1\126\50\0\1\127\47\0\1\130"+
    "\4\0\1\131\46\0\1\132\42\0\1\133\73\0\1\134"+
    "\35\0\1\135\3\0\1\136\37\0\1\137\51\0\1\140"+
    "\62\0\1\141\47\0\1\142\47\0\1\143\43\0\1\144"+
    "\44\0\1\145\1\146\22\0\4\147\1\6\4\147\1\150"+
    "\37\147\24\0\1\151\45\0\1\152\50\0\1\153\55\0"+
    "\1\154\66\0\1\155\35\0\1\156\43\0\1\157\52\0"+
    "\1\160\66\0\1\161\25\0\1\162\53\0\1\163\50\0"+
    "\1\164\60\0\1\165\42\0\1\166\43\0\1\167\71\0"+
    "\1\170\33\0\1\171\51\0\1\172\46\0\1\173\63\0"+
    "\1\174\35\0\1\175\55\0\1\176\45\0\1\177\61\0"+
    "\1\200\43\0\1\201\52\0\1\202\40\0\1\203\24\0"+
    "\4\52\1\204\4\52\1\112\43\52\1\205\4\52\1\112"+
    "\37\52\25\0\1\206\45\0\1\207\50\0\1\210\47\0"+
    "\1\211\54\0\1\212\47\0\1\213\50\0\1\214\50\0"+
    "\1\215\72\0\1\216\31\0\1\217\50\0\1\220\50\0"+
    "\1\221\46\0\1\222\44\0\1\223\54\0\1\224\3\0"+
    "\1\225\44\0\1\226\44\0\1\227\62\0\1\230\44\0"+
    "\1\231\45\0\1\232\52\0\1\233\53\0\1\234\51\0"+
    "\1\235\22\0\1\147\72\0\1\236\46\0\1\237\50\0"+
    "\1\240\46\0\1\241\57\0\1\242\51\0\1\243\43\0"+
    "\1\244\57\0\1\245\46\0\1\246\43\0\1\247\54\0"+
    "\1\250\45\0\1\251\46\0\1\252\56\0\1\253\46\0"+
    "\1\254\46\0\1\255\56\0\1\256\45\0\1\257\46\0"+
    "\1\260\52\0\1\261\51\0\1\262\37\0\1\263\16\0"+
    "\1\264\41\0\1\265\50\0\1\266\46\0\1\267\50\0"+
    "\1\270\57\0\1\271\43\0\1\272\46\0\1\273\45\0"+
    "\1\274\53\0\1\275\46\0\1\276\57\0\1\277\47\0"+
    "\1\300\47\0\1\301\37\0\1\302\52\0\1\303\52\0"+
    "\1\304\57\0\1\305\42\0\1\306\43\0\1\307\50\0"+
    "\1\310\50\0\1\311\61\0\1\312\43\0\1\313\47\0"+
    "\1\314\50\0\1\315\50\0\1\316\53\0\1\317\50\0"+
    "\1\320\54\0\1\321\44\0\1\322\45\0\1\323\51\0"+
    "\1\324\44\0\1\325\65\0\1\326\46\0\1\327\43\0"+
    "\1\330\62\0\1\331\45\0\1\332\45\0\1\333\50\0"+
    "\1\334\36\0\1\335\53\0\1\336\56\0\1\337\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7011];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\2\11\2\1\7\11\13\1\1\11\3\1\1\11"+
    "\1\1\2\11\1\1\2\11\1\1\1\11\4\0\1\11"+
    "\30\0\3\11\2\1\10\0\1\11\32\0\1\11\1\0"+
    "\1\11\3\0\1\11\11\0\1\11\7\0\1\1\5\0"+
    "\2\11\11\0\1\11\3\0\1\11\1\0\2\11\1\0"+
    "\2\11\2\0\1\1\3\0\2\11\6\0\1\11\7\0"+
    "\3\11\1\0\2\11\1\0\1\11\15\0\1\11\1\0"+
    "\3\11\3\0\1\11\1\0\1\11\3\0\1\11\4\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[223];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private String cadena = "";
    private int ban = 0;

    /**
    * Retorna el simbolo con sym.value
    * Con la linea, columna y texto de flex
    */
    private Symbol symbol(int value){
        return new Symbol(value, yyline, yychar, yytext());
    }

    /**
    * Retorna el simbolo con sym.id y valor asignado
    * Con la linea, columna de flex
    */
    private Symbol symbol(int id, Object value){
        return new Symbol(id, yyline, yychar, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public gxmlScanner(java.io.Reader in) {
      yyline = 1;
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 210) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { Constante.consola += "Este es un error lexico: "+yytext()+", en la linea: "+yyline+", en la columna: "+yychar+"\n";
            }
          case 56: break;
          case 2: 
            { 
            }
          case 57: break;
          case 3: 
            { return symbol(sym.entero);
            }
          case 58: break;
          case 4: 
            { yybegin(CADENA); cadena="";
            }
          case 59: break;
          case 5: 
            { yybegin(CARACTER); cadena="";
            }
          case 60: break;
          case 6: 
            { yybegin(LLAMADA); cadena="";
            }
          case 61: break;
          case 7: 
            { return symbol(sym.open);
            }
          case 62: break;
          case 8: 
            { return symbol(sym.close);
            }
          case 63: break;
          case 9: 
            { return symbol(sym.slash);
            }
          case 64: break;
          case 10: 
            { return symbol(sym.igual);
            }
          case 65: break;
          case 11: 
            { return symbol(sym.pr_x);
            }
          case 66: break;
          case 12: 
            { return symbol(sym.pr_y);
            }
          case 67: break;
          case 13: 
            { cadena+=String.valueOf(yytext());
            }
          case 68: break;
          case 14: 
            { yybegin(YYINITIAL); return symbol(sym.cadena, cadena);
            }
          case 69: break;
          case 15: 
            { cadena+=String.valueOf("\'");
            }
          case 70: break;
          case 16: 
            { cadena+=String.valueOf("\\");
            }
          case 71: break;
          case 17: 
            { cadena+=String.valueOf("\"");
            }
          case 72: break;
          case 18: 
            { yybegin(YYINITIAL);  return symbol(sym.cadena, cadena);
            }
          case 73: break;
          case 19: 
            { yybegin(YYINITIAL); return symbol(sym.llamada, cadena);
            }
          case 74: break;
          case 20: 
            { return symbol(sym.pr_id);
            }
          case 75: break;
          case 21: 
            { cadena+=String.valueOf("\r");
            }
          case 76: break;
          case 22: 
            { cadena+=String.valueOf("\t");
            }
          case 77: break;
          case 23: 
            { cadena+=String.valueOf("\n");
            }
          case 78: break;
          case 24: 
            { return symbol(sym.decimal);
            }
          case 79: break;
          case 25: 
            { return symbol(sym.pr_tam);
            }
          case 80: break;
          case 26: 
            { return symbol(sym.pr_path);
            }
          case 81: break;
          case 27: 
            { return symbol(sym.pr_tipo);
            }
          case 82: break;
          case 28: 
            { return symbol(sym.pr_alto);
            }
          case 83: break;
          case 29: 
            { return symbol(sym.pr_dato);
            }
          case 84: break;
          case 30: 
            { return symbol(sym.pr_texto);
            }
          case 85: break;
          case 31: 
            { return symbol(sym.pr_ancho);
            }
          case 86: break;
          case 32: 
            { return symbol(sym.pr_color);
            }
          case 87: break;
          case 33: 
            { return symbol(sym.pr_falso);
            }
          case 88: break;
          case 34: 
            { return symbol(sym.pr_borde);
            }
          case 89: break;
          case 35: 
            { return symbol(sym.pr_boton);
            }
          case 90: break;
          case 36: 
            { return symbol(sym.pr_minimo);
            }
          case 91: break;
          case 37: 
            { return symbol(sym.pr_maximo);
            }
          case 92: break;
          case 38: 
            { return symbol(sym.pr_accion);
            }
          case 93: break;
          case 39: 
            { return symbol(sym.pr_enviar);
            }
          case 94: break;
          case 40: 
            { return symbol(sym.pr_nombre);
            }
          case 95: break;
          case 41: 
            { return symbol(sym.pr_fuente);
            }
          case 96: break;
          case 42: 
            { return symbol(sym.pr_ventana);
            }
          case 97: break;
          case 43: 
            { return symbol(sym.pr_negrita);
            }
          case 98: break;
          case 44: 
            { return symbol(sym.pr_control);
            }
          case 99: break;
          case 45: 
            { return symbol(sym.pr_cursiva);
            }
          case 100: break;
          case 46: 
            { return symbol(sym.pr_defecto);
            }
          case 101: break;
          case 47: 
            { return symbol(sym.pr_importar);
            }
          case 102: break;
          case 48: 
            { return symbol(sym.pr_verdadero);
            }
          case 103: break;
          case 49: 
            { return symbol(sym.pr_listadato);
            }
          case 104: break;
          case 50: 
            { return symbol(sym.pr_multimedia);
            }
          case 105: break;
          case 51: 
            { return symbol(sym.pr_referencia);
            }
          case 106: break;
          case 52: 
            { return symbol(sym.pr_contenedor);
            }
          case 107: break;
          case 53: 
            { return symbol(sym.pr_accionfinal);
            }
          case 108: break;
          case 54: 
            { return symbol(sym.pr_accioninicial);
            }
          case 109: break;
          case 55: 
            { return symbol(sym.pr_autoreproduccion);
            }
          case 110: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
