
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gxml.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int slash = 4;
  public static final int pr_boton = 15;
  public static final int pr_ventana = 7;
  public static final int pr_ancho = 25;
  public static final int igual = 5;
  public static final int pr_cursiva = 31;
  public static final int pr_negrita = 30;
  public static final int pr_fuente = 28;
  public static final int pr_autoreproduccion = 37;
  public static final int pr_enviar = 16;
  public static final int llamada = 43;
  public static final int pr_verdadero = 40;
  public static final int pr_tam = 29;
  public static final int pr_alto = 24;
  public static final int pr_nombre = 27;
  public static final int open = 2;
  public static final int pr_importar = 6;
  public static final int EOF = 0;
  public static final int pr_y = 23;
  public static final int pr_listadato = 12;
  public static final int pr_x = 22;
  public static final int error = 1;
  public static final int entero = 38;
  public static final int pr_multimedia = 14;
  public static final int pr_color = 19;
  public static final int pr_contenedor = 8;
  public static final int pr_minimo = 33;
  public static final int pr_defecto = 13;
  public static final int pr_control = 10;
  public static final int pr_falso = 41;
  public static final int close = 3;
  public static final int pr_accionfinal = 21;
  public static final int pr_id = 17;
  public static final int pr_tipo = 18;
  public static final int pr_texto = 9;
  public static final int pr_path = 36;
  public static final int pr_dato = 11;
  public static final int pr_accioninicial = 20;
  public static final int pr_accion = 34;
  public static final int pr_borde = 26;
  public static final int pr_referencia = 35;
  public static final int decimal = 39;
  public static final int pr_maximo = 32;
  public static final int cadena = 42;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "open",
  "close",
  "slash",
  "igual",
  "pr_importar",
  "pr_ventana",
  "pr_contenedor",
  "pr_texto",
  "pr_control",
  "pr_dato",
  "pr_listadato",
  "pr_defecto",
  "pr_multimedia",
  "pr_boton",
  "pr_enviar",
  "pr_id",
  "pr_tipo",
  "pr_color",
  "pr_accioninicial",
  "pr_accionfinal",
  "pr_x",
  "pr_y",
  "pr_alto",
  "pr_ancho",
  "pr_borde",
  "pr_nombre",
  "pr_fuente",
  "pr_tam",
  "pr_negrita",
  "pr_cursiva",
  "pr_maximo",
  "pr_minimo",
  "pr_accion",
  "pr_referencia",
  "pr_path",
  "pr_autoreproduccion",
  "entero",
  "decimal",
  "pr_verdadero",
  "pr_falso",
  "cadena",
  "llamada"
  };
}

