
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gxml.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int slash = 3;
  public static final int pr_boton = 14;
  public static final int pr_ventana = 6;
  public static final int pr_ancho = 24;
  public static final int igual = 4;
  public static final int pr_cursiva = 30;
  public static final int pr_negrita = 29;
  public static final int nada = 43;
  public static final int pr_fuente = 27;
  public static final int pr_autoreproduccion = 36;
  public static final int pr_enviar = 15;
  public static final int llamada = 45;
  public static final int pr_verdadero = 39;
  public static final int pr_tam = 28;
  public static final int pr_alto = 23;
  public static final int pr_nombre = 26;
  public static final int open = 2;
  public static final int pr_importar = 5;
  public static final int EOF = 0;
  public static final int pr_y = 22;
  public static final int pr_listadato = 11;
  public static final int pr_x = 21;
  public static final int error = 1;
  public static final int entero = 37;
  public static final int pr_multimedia = 13;
  public static final int pr_color = 18;
  public static final int pr_contenedor = 7;
  public static final int pr_minimo = 32;
  public static final int pr_defecto = 12;
  public static final int pr_control = 9;
  public static final int fin = 44;
  public static final int pr_falso = 40;
  public static final int pr_accionfinal = 20;
  public static final int pr_id = 16;
  public static final int pr_tipo = 17;
  public static final int pr_texto = 8;
  public static final int pr_path = 35;
  public static final int pr_dato = 10;
  public static final int pr_accioninicial = 19;
  public static final int pr_accion = 33;
  public static final int pr_borde = 25;
  public static final int pr_referencia = 34;
  public static final int todo = 42;
  public static final int decimal = 38;
  public static final int pr_maximo = 31;
  public static final int cadena = 41;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "open",
  "slash",
  "igual",
  "pr_importar",
  "pr_ventana",
  "pr_contenedor",
  "pr_texto",
  "pr_control",
  "pr_dato",
  "pr_listadato",
  "pr_defecto",
  "pr_multimedia",
  "pr_boton",
  "pr_enviar",
  "pr_id",
  "pr_tipo",
  "pr_color",
  "pr_accioninicial",
  "pr_accionfinal",
  "pr_x",
  "pr_y",
  "pr_alto",
  "pr_ancho",
  "pr_borde",
  "pr_nombre",
  "pr_fuente",
  "pr_tam",
  "pr_negrita",
  "pr_cursiva",
  "pr_maximo",
  "pr_minimo",
  "pr_accion",
  "pr_referencia",
  "pr_path",
  "pr_autoreproduccion",
  "entero",
  "decimal",
  "pr_verdadero",
  "pr_falso",
  "cadena",
  "todo",
  "nada",
  "fin",
  "llamada"
  };
}

