
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package fs.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int pr_todos = 55;
  public static final int menos = 15;
  public static final int pr_funcion = 44;
  public static final int menor = 27;
  public static final int cori = 4;
  public static final int pr_crearreproductor = 70;
  public static final int cord = 5;
  public static final int punto = 8;
  public static final int pr_creartexto = 63;
  public static final int llai = 2;
  public static final int porigual = 24;
  public static final int pr_alguno = 56;
  public static final int llad = 3;
  public static final int pr_descendente = 45;
  public static final int div = 17;
  public static final int pr_alclic = 72;
  public static final int pr_sino = 43;
  public static final int pr_minimo = 50;
  public static final int divigual = 25;
  public static final int pr_caso = 40;
  public static final int mas = 14;
  public static final int cadena = 80;
  public static final int dospuntos = 10;
  public static final int menorigual = 29;
  public static final int pr_detener = 37;
  public static final int pr_imprimir = 36;
  public static final int decimal = 78;
  public static final int pr_selecciona = 39;
  public static final int pr_obtenerporetiqueta = 58;
  public static final int pr_creararraydesdearchivo = 47;
  public static final int pr_leergxml = 57;
  public static final int masigual = 22;
  public static final int or = 33;
  public static final int caracter = 81;
  public static final int pr_falso = 76;
  public static final int mayorigual = 28;
  public static final int pr_var = 35;
  public static final int id = 79;
  public static final int pr_invertir = 48;
  public static final int inter = 12;
  public static final int menmen = 20;
  public static final int pr_creardespegable = 67;
  public static final int pr_alcerrar = 74;
  public static final int ptcoma = 9;
  public static final int and = 32;
  public static final int mayor = 26;
  public static final int pr_buscar = 52;
  public static final int pr_retornar = 38;
  public static final int pr_alcargar = 73;
  public static final int pr_crearcontrolnumerico = 66;
  public static final int pr_crearventana = 61;
  public static final int EOF = 0;
  public static final int pr_ascendente = 46;
  public static final int pr_si = 42;
  public static final int pr_crearboton = 68;
  public static final int pr_map = 53;
  public static final int error = 1;
  public static final int diferente = 31;
  public static final int pr_reduce = 54;
  public static final int entero = 77;
  public static final int pr_crearcontenedor = 62;
  public static final int pr_crearareatexto = 65;
  public static final int UMENOS = 21;
  public static final int pr_defecto = 41;
  public static final int pari = 6;
  public static final int igualigual = 30;
  public static final int pr_verdadero = 75;
  public static final int pr_obtenerpornombre = 60;
  public static final int pot = 18;
  public static final int pard = 7;
  public static final int por = 16;
  public static final int pr_crearimagen = 69;
  public static final int pr_crearcajatexto = 64;
  public static final int pr_crearvideo = 71;
  public static final int coma = 11;
  public static final int not = 34;
  public static final int igual = 13;
  public static final int pr_filtrar = 51;
  public static final int menigual = 23;
  public static final int masmas = 19;
  public static final int pr_obtenerporid = 59;
  public static final int pr_maximo = 49;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "llai",
  "llad",
  "cori",
  "cord",
  "pari",
  "pard",
  "punto",
  "ptcoma",
  "dospuntos",
  "coma",
  "inter",
  "igual",
  "mas",
  "menos",
  "por",
  "div",
  "pot",
  "masmas",
  "menmen",
  "UMENOS",
  "masigual",
  "menigual",
  "porigual",
  "divigual",
  "mayor",
  "menor",
  "mayorigual",
  "menorigual",
  "igualigual",
  "diferente",
  "and",
  "or",
  "not",
  "pr_var",
  "pr_imprimir",
  "pr_detener",
  "pr_retornar",
  "pr_selecciona",
  "pr_caso",
  "pr_defecto",
  "pr_si",
  "pr_sino",
  "pr_funcion",
  "pr_descendente",
  "pr_ascendente",
  "pr_creararraydesdearchivo",
  "pr_invertir",
  "pr_maximo",
  "pr_minimo",
  "pr_filtrar",
  "pr_buscar",
  "pr_map",
  "pr_reduce",
  "pr_todos",
  "pr_alguno",
  "pr_leergxml",
  "pr_obtenerporetiqueta",
  "pr_obtenerporid",
  "pr_obtenerpornombre",
  "pr_crearventana",
  "pr_crearcontenedor",
  "pr_creartexto",
  "pr_crearcajatexto",
  "pr_crearareatexto",
  "pr_crearcontrolnumerico",
  "pr_creardespegable",
  "pr_crearboton",
  "pr_crearimagen",
  "pr_crearreproductor",
  "pr_crearvideo",
  "pr_alclic",
  "pr_alcargar",
  "pr_alcerrar",
  "pr_verdadero",
  "pr_falso",
  "entero",
  "decimal",
  "id",
  "cadena",
  "caracter"
  };
}

