/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package creator_xml;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rtextarea.RTextScrollPane;
import otros.Constante;

/**
 *
 * @author Jhona
 */
public class principal extends javax.swing.JFrame {

    String[] options_name = { "GenericXML", "FuncionScript" };
    String[] options_ext =  { "gxml", "fs" };
    
    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
        Constante.consola = "";
        addTab("Archivo_1", "gxml");
    }
    
    public void opcionCrearTab(){
        //debo de pedir el nombre del archivo y su extension
        String nombre = JOptionPane.showInputDialog(null, "Ingrese el nombre del archivo", 
                " Nombre Tab", JOptionPane.INFORMATION_MESSAGE);
        
        if(nombre != null){
            if(!nombre.equals(""))
            {
                String extension = (String)JOptionPane.showInputDialog(null, 
                    "Seleccione el tipo de archivo", "Extension", JOptionPane.INFORMATION_MESSAGE, 
                    null, options_name, options_name[0]);

                extension = (extension.equals(options_name[0]))?options_ext[0]:options_ext[1];

                addTab(nombre, extension);
            }
            else { JOptionPane.showMessageDialog(null, "Debe ingresar el nombre", "Informe de error", JOptionPane.ERROR_MESSAGE); }
        }
    }
    
    public void addTab(String nombre, String extension){
        
        //Colocar area de texto
        RSyntaxTextArea rsta = new RSyntaxTextArea();
        
        //Colocar un scrollpane
        RTextScrollPane rtsp = new RTextScrollPane(rsta, true);
        rtsp.setFoldIndicatorEnabled(true);
        rtsp.setIconRowHeaderEnabled(true);
        
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(rtsp, BorderLayout.CENTER);
        
        String nameTab = nombre + "." + extension;
        tabcontrol.addTab(nameTab, pan);
    }
    
    public void interpretar(){
        Constante.consola = "";
        
        String nombre = tabcontrol.getTitleAt(tabcontrol.getSelectedIndex());
        
        JPanel pan =(JPanel)(tabcontrol.getSelectedComponent());
        RTextScrollPane rtsp = (RTextScrollPane) pan.getComponent(0);
        RSyntaxTextArea texto = (RSyntaxTextArea) rtsp.getTextArea();
        
        if(nombre.endsWith(".gxml")){
            Creator_XML.analizarGXML(texto.getText());
        }
        else{
            Creator_XML.analizarFS(texto.getText());
        }
        
        consola.setText(Constante.consola);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_compilar = new javax.swing.JButton();
        tabcontrol = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        consola = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btn_abrir = new javax.swing.JMenuItem();
        btn_guardar = new javax.swing.JMenuItem();
        btn_guardarcomo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btn_nuevo = new javax.swing.JMenuItem();
        btn_cerrar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btn_report = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_compilar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/icons8-reproducir-en-círculo-48.png"))); // NOI18N
        btn_compilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_compilarActionPerformed(evt);
            }
        });

        consola.setColumns(20);
        consola.setRows(5);
        jScrollPane1.setViewportView(consola);

        jMenu1.setText("Archivo");

        btn_abrir.setText("Abrir");
        jMenu1.add(btn_abrir);

        btn_guardar.setText("Guardar");
        jMenu1.add(btn_guardar);

        btn_guardarcomo.setText("Guardar Como");
        jMenu1.add(btn_guardarcomo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Pestaña");

        btn_nuevo.setText("Nuevo Tab");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });
        jMenu2.add(btn_nuevo);

        btn_cerrar.setText("Cerrar Tab");
        jMenu2.add(btn_cerrar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Errores");

        btn_report.setText("Reporte Errores");
        jMenu3.add(btn_report);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tabcontrol))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(560, 560, 560)
                .addComponent(btn_compilar)
                .addContainerGap(559, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_compilar)
                .addGap(10, 10, 10)
                .addComponent(tabcontrol, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        opcionCrearTab();
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void btn_compilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_compilarActionPerformed
        // TODO add your handling code here:
        interpretar();
    }//GEN-LAST:event_btn_compilarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btn_abrir;
    private javax.swing.JMenuItem btn_cerrar;
    private javax.swing.JButton btn_compilar;
    private javax.swing.JMenuItem btn_guardar;
    private javax.swing.JMenuItem btn_guardarcomo;
    private javax.swing.JMenuItem btn_nuevo;
    private javax.swing.JMenuItem btn_report;
    private javax.swing.JTextArea consola;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabcontrol;
    // End of variables declaration//GEN-END:variables
}
